### ISSUE TITLE
automated dockerhub builds

### ISSUE THREAD

**Issue by kaczmarj** [neuronets/ams#2]
dockerhub does not copy the .git directory, which leads to issues at container build time. `git-annex` seems to need some information about the git repository before it can fetch the model file. this has led to automated build failures. for now, i have manually pushed `neuronets/ams:latest-cpu` and `neuronets/ams:latest-gpu`.

**Comment by satra** [comment]
@kaczmarj - you would have to initialize the git annex bit separately.  we could use a separate repo for the data (e.g. nobrainer-models). during the build fetch that repo and get the relevant modules.

**Comment by kaczmarj** [comment]
@satra - that's a great idea. i'll set that up. might take me a few days. do you have any suggestions for naming conventions and/or directory structure?

**Comment by satra** [comment]
something like: `groupname/modelname/<data>`

for example:
`kwyk: nimh/kwyk`
`aims: sig/aims`
`psacnn: freesurfer/psacnn`

**Comment by kaczmarj** [comment]
automated dockerhub builds are now working... see https://hub.docker.com/r/neuronets/ams
